# -*- coding: utf-8 -*-
"""07-04-22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13cULXqfsVOU1F5Z5DfcU8uGo0WGq2mml
"""

x = input("Ingrese opción ")
if x == "A":
  print("Opción de registro")
elif x == "B":
  print("Opción de login")
else: 
  print("Opción no válida para el inicio de sesión")

numA = float(input("Ingrese número A "))
numB = float(input("Ingrese número B "))
suma = numA + numB
print("El resultado de la suma es: " , suma)
if numA >= numB:
  resta = numA - numB
else:
  resta = numB- numA
print("El resultado de la resta es: " , resta)
numC = float(input("Ingrese número C "))
mult = resta * numC
print("El resultado de la multiplicación es: " , mult)
numD = float(input("Ingrese número D "))
if numC < numD:
  div = numD / numC
else:
  div = numC / numD
print("El resultado de la división es: " , div)