# -*- coding: utf-8 -*-
"""07-04-22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13cULXqfsVOU1F5Z5DfcU8uGo0WGq2mml
"""

x = input("Ingrese opción ")
if x == "A":
  print("Opción de registro")
elif x == "B":
  print("Opción de login")
else: 
  print("Opción no válida para el inicio de sesión")

numA = float(input("Ingrese número A "))
numB = float(input("Ingrese número B "))
suma = numA + numB
print("El resultado de la suma es: " , suma)
if numA >= numB:
  resta = numA - numB
else:
  resta = numB- numA
print("El resultado de la resta es: " , resta)
numC = float(input("Ingrese número C "))
mult = resta * numC
print("El resultado de la multiplicación es: " , mult)
numD = float(input("Ingrese número D "))
if numC < numD:
  div = numD / numC
else:
  div = numC / numD
print("El resultado de la división es: " , div)

for i in range(1, 100):
  if i%2 == 0:
    continue
  print("El número es impar: ", i)

num1 = float(input("Ingrese número 1: "))
num2 = float(input("Ingrese número 2: "))
x=1
suma = num1 + num2
while suma < 100:
  print("Suma " , x , ": " , suma)
  if num1 >= 40 or num2 >= 40:
    break
  x += 1
  suma += suma
  if suma>=100:
    print("Suma " , x , ": " , suma)

num1 = float(input("Ingrese número 1: "))
num2 = float(input("Ingrese número 2: "))
x=1
suma1 = num1 + num2
suma = suma1
while suma < 100:
  print("Suma " , x , ": " , suma)
  if num1 >= 40 or num2 >= 40:
    break
  x += 1
  suma += suma1
  if suma>=100:
    print("Suma " , x , ": " , suma)

cadena = input("Ingrese cadena de texto (más de 5 caracteres) ")
x=0
for i in cadena:
  x += 1
if x>5:
  for i in cadena:
    print(i)
  print("El tamaño del texto insertado es de " , x , " caracteres")
else:
  print("Las palabras insertadas deben ser mayores a 5 caracteres")