# -*- coding: utf-8 -*-
"""28-04-22 (Listas).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIfSqb_5gNf20DWt_OglWDuYYiydNsUs
"""

numericos=[1, 3, 10, 11, 13, 14, 17, 24, 26, 30]
combinados=[11, "Mariana", 1.11, "Capricornio", 1.57, "Biología", 2004, "Mia", 18, "Otoño"]
texto=["se", "debe", "crear", "una", "lista", "de", "diez", "valores", "de", "texto"]
numericos[0]=20
combinados[0]=20
texto[0]=20
numericos[5]="hola mundo"
combinados[5]="hola mundo"
texto[5]="hola mundo"
print(numericos[9])
print(combinados[9])
print(texto[9])