# -*- coding: utf-8 -*-
"""28-04-22 (Funciones)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x-BD1MkuPspWf-aefBId5PaWCZj1H4Xg
"""

def multiplicacion():
  num=float(input("Ingrese número: "))
  num=num*(num+1)
  print("Resultado: " , num)
for i in range(0,5):
  multiplicacion()

def multiplicacion():
  num=float(input("Ingrese número: "))
  num=num*(num+1)
  return num
for i in range(0,5):
  resultado=multiplicacion()
  print("El resultado de la operación es: ", resultado)

def multiplicacion():
  num=float(input("Ingrese número: "))
  num=num*(num+1)
  print("Resultado: " , num)
def division():
  num=float(input("Ingrese número: "))
  num=num/(num+1)
  print("Resultado: " , num)
def suma():
  num=float(input("Ingrese número: "))
  num=num+(num+1)
  print("Resultado: " , num)
def resta():
  num=float(input("Ingrese número: "))
  num=num-(num+1)
  print("Resultado: " , num)
opcion=input("Indique qué operación desea realizar (A. Suma // B. Resta // C. Multiplicación // D. División): ")
x=0
while x<5:
  if opcion=="A":
    suma()
  elif opcion=="B":
    resta()
  elif opcion=="C":
    multiplicacion()
  if opcion=="D":
    division()
  x+=1