# -*- coding: utf-8 -*-
"""31-03-22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17RpyIdZ5gqe4Cl31kl-MnJoJ8BQjm52s
"""

numero1 = int(input("Ingresa el número 1 para la suma "))
numero2 = int(input("Ingresa el número 2 para la suma "))
suma = numero1 + numero2
print("El resultado de la suma es: " , suma)

numero3 = int(input("Ingresa el número 1 para la resta "))
numero4 = int(input("Ingresa el número 2 para la resta "))
resta = numero3 - numero4
print("El resultado de la resta es: " , resta)

division = suma / resta
print("El resultado de la división es " , division)

multiplicacion = suma * resta
print("El resultado de la multiplicación es " , multiplicacion)

nota11 = float(input("Ingrese nota 1 del corte 1: "))
nota12 = float(input("Ingrese nota 2 del corte 1: "))
nota13 = float(input("Ingrese nota 3 del corte 1: "))
suma1 = nota11 + nota12 + nota13
prom1 = suma1 / 3
corte1 = prom1 * 0.2
print("La nota para el corte 1 es: " , prom1)

nota21 = float(input("Ingrese nota 1 del corte 2: "))
nota22 = float(input("Ingrese nota 2 del corte 2: "))
nota23 = float(input("Ingrese nota 3 del corte 2: "))
suma2 = nota21 + nota22 + nota23
prom2 = suma2 / 3
corte2 = prom2 * 0.2
print("La nota para el corte 2 es: " , prom2)

nota31 = float(input("Ingrese nota 1 del corte 3: "))
nota32 = float(input("Ingrese nota 2 del corte 3: "))
nota33 = float(input("Ingrese nota 3 del corte 3: "))
suma3 = nota31 + nota32 + nota33
prom3 = suma3 / 3
corte3 = prom3 * 0.6
print("La nota para el corte 3 es: " , prom3)

total = corte1 + corte2 + corte3
print("La nota total es: " , total)

prod1 = float(input("Ingrese valor del producto 1: "))
iva1 = prod1 * 1.19
print("El valor del producto 1 con el IVA aplicado es: " , iva1)

prod2 = float(input("Ingrese valor del producto 2: "))
iva2 = prod2 * 1.19
print("El valor del producto 2 con el IVA aplicado es: " , iva2)

prod3 = float(input("Ingrese valor del producto 3: "))
iva3 = prod3 * 1.19
print("El valor del producto 3 con el IVA aplicado es: " , iva3)

total = iva1 + iva2 + iva3
print("El total a pagar es: " , total)