# -*- coding: utf-8 -*-
"""5 de mayo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ZDImgy4Al6bNkUtaK0Q_ykITe2iSA0R
"""

#ejercicios de lista#
lista=[]
for x in range(0,10):
 x+=1
 num=int(input("ingrese un número: "))
 lista.append(num)
print(lista)
len(lista)
lista.pop()

#tuplas#
tupla=(1,2,3,4,5,("a","b","c"), True, False)
print(tupla[0])
print(tupla[7])
tupla1=(1,2,3,4,5,6,7,8,9,10,11)
tupla2=(2,4,6,8,5)
tupla3=("no","me","gusta","jairo","mariana","deje","la","groseria")
if len(tupla)>len(tupla1)and len(tupla)>len(tupla2)and len(tupla)>len(tupla3):
  print("la dupla con más elementos es: ",tupla)
elif len(tupla)<len(tupla1)and len(tupla2)<len(tupla1)and len(tupla3)<len(tupla1):
  print("la dupla con más elementos es: ",tupla1)
elif len(tupla)<len(tupla2)and len(tupla1)<len(tupla2)and len(tupla2)>len(tupla3):
  print("la dupla con más elementos es: ",tupla2)
else:
  print("la dupla con más elementos es: ",tupla3)

numero=int(input("numero"))
def par_impar(numero):

    if(numero%2)==0:
        return True
    else:
        return False
  
resultado=par_impar(2)

if resultado==True:
    print("El número es par")
else:
    print("El número es impar")

for i in range(1,100):

   print(i)