# -*- coding: utf-8 -*-
"""Actividades semana 11 - clase 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17a5JTT2hGILRKlYQipOOpizAzs4L4V-m

# Semana 11 - Clase N°9 Phyton
"""

print ("Bienvenido al menú de opciones")
X=str(input("Ingrese una opción A, B o C "))
X=X.upper
if X == "A":
  print ("Opción de Registro")
elif X == "B":
  print ("Opción de Login")
else:
  print ("Opción no válida para el incio de sesión")

print ("Bienvenido a su calculadora de restas")
n1=int(input("Ingrese un entero como minuendo: "))
n2=int(input("Ingrese un entero como sustraendo: "))
while n2>n1:
  print ("El sustraendo no puede ser mayor al minuendo, ingrese valores diferentes")
  n1=int(input("Ingrese minuendo: "))
  n2=int(input("Ingrese sustraendo: "))
resta=n1-n2
print ("El resultado de su resta es :", resta)

print ("Bienvenido a su calculadora de restas")
n1=input("Número 1: ")
n2=input("Número 2: ")
while n1 and n2 != int:
  print ("Los números deben ser enteros, ingrese de nuevo los valores")
  n1=int(input("Número 1: "))
  n2=int(input("Número 2: "))
  break
if n1 > n2:
  resta=n1-n2
  print ("El resultado de su resta es :", resta)
elif n2 > n1:
  resta=n2-n1
  print ("El resultado de su resta es :", resta) 

n4=resta

n3=int(input("Ingrese otro número: "))
if n3 > n4:
  division=n3/n4
  print ("El resultado de su división es :", division)
elif n4 > n3:
  division=n4/n3
  print ("El resultado de su división es :", division)

for i in range (1, 100):
  if i % 2 == 0:
    continue
  else:
    print (i)

print ("Bienvenido")
n1=int(input("Número 1: "))
n2=int(input("Número 2: "))
suma=n1+n2

while suma < 100:
  if n1 <= 40 or n2 <= 40:
    suma+=n1+n1
    print (suma)
  else:
    break

txt=input("Bienvenido. Ingrese texto ")
letras=0
for i in txt:
  if (i.isalpha()):
    letras+=1
if letras < 6:
  print ("El texto ingresado debe contener más de 5 caracteres")
else:
  print ("El número de letras que contiene el texto es: ", letras)