# -*- coding: utf-8 -*-
"""Actividades Semana 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17zzo2McEJnMfcz6o95t6WDjVPV_hTU8j
"""

numero_1= int(input("ingrese número 1 "))
numero_2= int (input("ingrese número 2 "))
suma = numero_1 + numero_2
resta = numero_1 - numero_2
división = suma/resta
multiplicación = suma * resta

print ("El resultado de la suma es: " , suma)
print ("El resultado de la resta es: ", resta)
print ("El resultado de la división es: ", división)
print ("El resultado de la multiplicación ", multiplicación)

print ("Bienvenido. A continuación digite las notas de sus respectivos cortes")
print ("Notas primer corte")
a1= float(input("Ingrese nota 1: "))
a2= float(input("Ingrese nota 2: "))
a3= float(input("Ingrese nota 3: "))
promedio1= (a1+a2+a3)/3
print ("Promedio primer corte: ", promedio1)

print ("Notas segundo corte")
b1= float(input("Ingrese nota 1: "))
b2= float(input("Ingrese nota 2: "))
b3= float(input("Ingrese nota 3: "))
promedio2= (b1+b2+b3)/3
print ("Promedio segundo corte: ", promedio2)

print ("Notas segundo corte")
c1= float(input("Ingrese nota 1: "))
c2= float(input("Ingrese nota 2: "))
c3= float(input("Ingrese nota 3: "))
promedio3= (c1+c2+c3)/3
print ("Promedio segundo corte: ", promedio3)

corte_1= promedio1 * 0.2
corte_2= promedio2 * 0.2
corte_3= promedio3 * 0.6
nota_final= corte_1 + corte_2 + corte_3
print ("Su nota final es de: ", nota_final)

print ("Bienvenido. Ingrese el valor de los productos")
p1=float(input("Valor producto 1: "))
p2=float(input("Valor producto 2: "))
p3=float(input("Valor producto 3: "))

iva1=p1+p1*0.19
iva2=p2+p2*0.19
iva3=p3+p3*0.19
total=iva1+iva2+iva3

print ("Así se ven sus productos con iva :")
print ("producto 1: $", iva1)
print ("producto 2: $", iva2)
print ("producto 3: $", iva3)

print ("El total a pagar es: $", total)