# -*- coding: utf-8 -*-
"""CLASE 9 CORTE 2 SOC

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNgGbGRORiWpIoY-IOkH_aPcbOy2RXkg
"""

#Captura datos de un usuario a través de la consola, y valida el valor 
#para así crear un menú de opciones, si el texto ingresado es A, 
#mostrar el mensaje "Opción de Registro", si es B mostrar "Opción de Login", 
#si es C o cualquier otra letra indicar que no es valida la 
#opción para el inicio de sesión.

let = str(input("Escoja A, B o C para el menú de opciónes (por favor escibir con mayúsculas la letra): "))

if let == "A":
  print("Opción de Registro")
elif let == "B": 
  print("Opción de Login")
elif let == "C": 
  print("No es valida la opcion para el inicio de sesión")

#Capture 2 número y sumelos, para la resta valide que 
#el número A sea mayor que el número B, 
#de lo contrario la resta debería ser B - A (Esto para evitar número negativos). 
#Luego pida nuevamente un número y realice la multiplicación 
#entre el valor de la resta y el digito acabado de ingresar. 
#Ingrese nuevamente un número D y valide si es menor o mayor a C. 
#En caso de que D sea mayor deberá ser el dividendo, el menor debe ser el divisor.

print("inserte un número A:")
a= int(input())

print("inserte número B: ")
b= int(input()) 

sum=a+b
print("la suma de los dos numeros es:"+ str(sum))

###########################

if (a > b):
  rest= a-b
else: 
  rest= b-a
print("la resta de los dos numeros es:"+ str(rest))

##########################

print("inserte número C: ")
c= int(input()) 

##########################

mult= rest*c
print("El resultado de la multiplicación es:"+ str(mult))

##########################

print("inserte número D: ")
d= int(input()) 

if (d > c):
  div=d/c
else:
  div=c/d

print("El resultado de la divición es:"+ str(div))

##CICLOS##

#Crea un rango de números del 1 al 100 donde valides si este es par o impar, 
#si el número es par deberás hacer un continue, de lo contrario mostrar un mensaje con el número. 
#El resultado de este ejercicio es obtener todos los números impares del 1 a 100

for i in range (101):

  if i%2==0:
    print(i, "continue (es par)")
  else:
    print(i, "es impar")

#Reciba dos número en pantalla y realice la suma de ambos números, siga sumando 
#los números ingresados con el resultado de la suma hasta que el resultado sea mayor a 100. 
#Rompa el ciclo con break si uno de los 2 números es mayor o igual a 40.

num1= int(input("Ingrese número 1: "))
num2= int(input("Ingrese número 2: "))

suma=num1+num2
 
while suma <= 100: 
  if num1 >= 40 or num2 >= 40:
    break
  else:
    suma=suma+num1+num2
    print(suma)

#Ingrese una cadena de texto por consola y muestre cada letra de manera independiente
#haciendo uso del for, luego, cuando finalice el ciclo, muestre el tamaño del texto insertado. 
#Las palabras que inserte deben ser mayores a 5 caracteres, haga una validación para garantizar esto.

cadena= str(input("Ingrese el texto: "))
for i in (cadena):
  print(i)
print("el tamaño del texto insertado es:", len (cadena))