# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHGiTz5AuMUxfyoDaPKZVSO5CPL3jKt7
"""

Numero1 = int(input("ingrese un número para la suma")) 
Numero2 = int(input("ingrese otro número para la suma")) 

Suma = Numero1 + Numero2
print("el número obtenido de la suma es:", Suma)

Numero3 = int(input("ingrese un número para la resta")) 
Numero4 = int(input("ingrese otro número para la resta")) 

Resta = Numero3 + Numero4
print("el resultado de la resta es:", Resta)

division= Suma/Resta
print ("el resultado de la división entre el resultado de la suma y la resta es", division)

Multiplicacion= Suma*Resta
print ("el resultado de la multiplicación entre el resultado de la suma y la resta es", Multiplicacion)

print ("Notas del corte 1")
Nota1_1 = float(input("ingrese la nota 1 del corte 1 ")) 
Nota1_2 = float(input("ingrese la nota 2 del corte 1 ")) 
Nota1_3 = float(input("ingrese la nota 3 del corte 1 ")) 
Suma_corte_1=Nota1_1+Nota1_2+Nota1_3
Promedio_corte_1=Suma_corte_1/3
corte1= Promedio_corte_1*0.20
print("el promedio del corto es" , Promedio_corte_1)

print ("Notas del corte 2")
Nota2_1 = float(input("ingrese la nota 1 del corte 2 ")) 
Nota2_2 = float(input("ingrese la nota 2 del corte 2 ")) 
Nota2_3 = float(input("ingrese la nota 3 del corte 2 ")) 
Suma_corte_2=Nota2_1+Nota2_2+Nota2_3
Promedio_corte_2=Suma_corte_2/3
corte2= Promedio_corte_2*0.20
print("el promedio del corto es" , Promedio_corte_2)

print ("Notas del corte 3")
Nota3_1 = float(input("ingrese la nota 1 del corte 3 ")) 
Nota3_2 = float(input("ingrese la nota 2 del corte 3 ")) 
Nota3_3 = float(input("ingrese la nota 3 del corte 3 ")) 
Suma_corte_3=Nota3_1+Nota3_2+Nota3_3
Promedio_corte_3=Suma_corte_3/3
corte3= Promedio_corte_3*0.60
print("el promedio del corto es 2" , Promedio_corte_1)
Promedio_total = corte1 + corte2 + corte3

print("la nota total es de ", Promedio_total)

print ("Calculadora del 19%")
P1 = float(input("ingrese el precio del producto 1 ")) 
IVA1= P1*0.19
Valor1= IVA1+P1
print ("el costo del producto incluyendo el IVA es de ", Valor1)

P2 = float(input("ingrese el precio del producto 2 ")) 
IVA2= P2*0.19
Valor2= IVA2+P2
print ("el costo del producto incluyendo el IVA es de ", Valor2)

P3 = float(input("ingrese el precio del producto 3 ")) 
IVA3= P3*0.19
Valor3= IVA3+P3
print ("el costo del producto incluyendo el IVA es de ", Valor3)

Total=Valor1+Valor2+Valor3
print ("el valor a pagar es ", Total)