# -*- coding: utf-8 -*-
"""Clase 19 de mayo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kWcmw2w45WQ1GuJ7l0zmIdqxsLCtCU6x
"""

class bacteria:
  def __init__(self,especie, respiracion ,gram, metabolismo, morfologia):
    self.especie=especie
    self.respiracion=respiracion
    self.gram=gram
    self.metabolismo=metabolismo
    self.morfologia=morfologia

  def ver_informacion(self):
    return f" {self.especie} es {self.respiracion}, es Gram {self.gram}, su metabolismo es {self.metabolismo} y su morfologia es {self.morfologia}"
   
class mibacteria(bacteria):
  pass

b= mibacteria("Bacillus thirugensis", "aerobica", "Positiva", "reductora de nitrogeno", "bacilo" )
b.ver_informacion()

class figura:
  def __init__(self, base, altura):
  self.base=base
  self.altur=altura

  def calculo_del_area():
  area=self.base*self.altura

    
class triangulo(figura):
  def calculo_area(self):

base=input()
  t=triangulo(3,4)
  print(t.calculo_del_area())

def saludar():
  print ("hola mundo")

saludar()

list=[]
for i in range(1,101):
  list.append(i)
print(list)

nombre=input("nombre peli")
categoria=input("categoria peli")
duracion=input("duracion peli")

diccionario={
    "nombre":nombre,
    "categoria":categoria,
    "duracion":duracion
}
print (diccionario)

class vehiculo:
  def __init__ (self,marca, kilometraje, color):
    self.marca=marca
    self.kilometraje=kilometraje
    self.color=color
  def ver_informacion(self):
    return f" su carro es {self.marca}, tiene un kilometraje {self.kilometraje} y su color es {self.color}"
   
class carro(vehiculo):
  pass

c= carro("toyota", "60.000", "negro " )
c.ver_informacion()

list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
def listadenumero(list):
  for i in list:
    if (i%2)==0:
      print("Buzz")
    elif (i%5)==0:
      print("Fizz")

listadenumero(list)