# -*- coding: utf-8 -*-
"""Clase_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TGmcG5u0_4ruq7MsGpJNqfiEN1yyWE1
"""

numero1=float(input("ingrese un numero para la operacion A "))
numero2=float(input("ingrese un numero para la operacion B "))
numero3=float(input("ingrese un numero para la operacion C "))
numero4=float(input("ingrese un numero para la operacion D "))
numero5=float(input("ingrese un numero para la operacion E "))

suma1= numero1+ 1
multiplicacion1= numero1* suma1
print("el resultado de la operacion A es:", multiplicacion1)

suma2= numero2+ 1
multiplicacion2= numero2* suma2
print("el resultado de la operacion B es:", multiplicacion2)

suma3= numero3+ 1
multiplicacion3= numero3* suma3
print("el resultado de la operacion C es:", multiplicacion3)

suma4= numero4+ 1
multiplicacion4= numero4* suma4
print("el resultado de la operacion D es:", multiplicacion4)

suma5= numero5+ 1
multiplicacion5= numero5* suma5
print("el resultado de la operacion E es:", multiplicacion5)

#funcion clase 11
opcion=str(input("Ingresa la el nombre de la operacion que quieras realizar: "))
def multiplicacion():
      num=int(input("Ingresa un número"))
      num=num*(num+1)
      print("El resultado es ",num)
def division():
        num=int(input("Ingresa un número"))
        num=num/(num+1)
        print("El resultado es ", num)
def suma():
    num=int(input("Ingresa un número"))
    num=num+(num+1)
    print("El resultado es ", num)
def resta():
        num=int(input("Ingresa un número"))
        num=num-(num+1)
        print("El resultado es ", num)
x=0
for i in range (0,5) :
    if opcion=="multiplicacion":
        multiplicacion()
    elif opcion=="division":
        division()
    elif opcion=="suma":
        suma()
    elif opcion=="resta":
        resta()
    x=x+1