# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19TGmcG5u0_4ruq7MsGpJNqfiEN1yyWE1
"""

numero1=float(input("ingrese un numero para la variable A "))
numero2=float(input("ingrese un numero para la variable B "))
suma= numero1+ numero2
print("el resultado de la suma es:", suma)

if numero1 > numero2:
  resta1= numero1-numero2
  print("el resultado de la resta es:", resta1)
else:
    resta2= numero2-numero1
    print("el resultado de la resta es:", resta2)

numero3=float(input("ingrese un numero para la variable C "))
if numero1 > numero2:
  multiplicacion1= resta1*numero3
  print("el resultado de la multiplicacion es:", multiplicacion1)
else:
   multiplicacion2= resta2*numero3
   print("el resultado de la multiplicacion es:", multiplicacion2)

numero4=float(input("ingrese un numero para la variable D "))
if numero3 > numero4:
  division1= numero3/numero4
  print("el resultado de la division es:", division1)
else:
  division2= numero4/numero3
  print("el resultado de la division es:", division2)