# -*- coding: utf-8 -*-
"""Clase 8 Ana Maria Alzate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15GDpul0VMiUoMN8DyqyMERJwUWbF_Xyk
"""

num1 = int(input("Ingresa el primer número de la suma"))
num2 = int(input("Ingresa el segundo número de la suma"))
suma = num1 + num2
print("El resultado de la suma es " , suma)

num3 = int(input("Ingresa el primer número de la resta"))
num4 = int(input("Ingresa el segundo número de la resta"))
resta = num3 - num4
print("El resultado de la resta es " , resta)

division = suma/resta
print("El resultado de la división del resultado de la suma entre el de la resta es es " , division)

multiplicacion= suma * resta
print("El resultado de la multiplicacion del resultado de la suma por el de la resta es es " , multiplicacion)

a1 = float(input("Ingresa la primera nota del corte 1"))
a2 = float(input("Ingresa la segunda nota del corte 1"))
a3 = float(input("Ingresa la tercera nota del corte 1"))
prom1 = ((a1+a2+a3)*0.2)/3

b1 = float(input("Ingresa la primera nota del corte 2"))
b2 = float(input("Ingresa la segunda nota del corte 2"))
b3 = float(input("Ingresa la tercera nota del corte 2"))
prom2 = ((b1+b2+b3)*0.2)/3

c1 = float(input("Ingresa la primera nota del corte 3"))
c2 = float(input("Ingresa la segunda nota del corte 3"))
c3 = float(input("Ingresa la tercera nota del corte 3"))
prom3 = ((c1+c2+c3)*0.6)/3

nota= prom1 + prom2 + prom3
print("La nota final de su materia es " , nota)

p1 = float(input("Ingresa el valor del primer producto del supermercado"))
p2 = float(input("Ingresa el valor del segundo producto del supermercado"))
p3 = float(input("Ingresa el valor del tercer producto del supermercado"))

iva1 = p1*0.19+p1
print("El valor del primer producto con iva es " , iva1) 

iva2 = p2*0.19+p2
print("El valor del segundo producto con iva es " , iva2) 

iva3 = p3*0.19+p3
print("El valor del tercer producto con iva es " , iva3) 

valorpago = iva1+iva2+iva3

print("El total a pagar es " , valorpago)

