# -*- coding: utf-8 -*-
"""Clase 12 de mayo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g_GFOm_rWXfwcLXGwA8J3HW_8X7PWno4
"""

#ejericios de repaso#
lista=[]
for i in range(2,301):
  if (i%2)==0: 
    lista.append(i)
print(lista)

nv=0
lista=[]
while nv < 5:
  print("Ingrese los siguientes datos:  ")
  nombre=input("nombre: ")
  apellido=input("apellido: ")
  edad=input("edad: ") 
  telefono=input("telefono: ") 
  correo=input("correo: ")
  diccionario={"nombre": nombre,"Apellido": apellido, "Edad": edad, "Telefono": telefono, "correo": correo}
  nv+=1
  lista.append(diccionario)
print(lista)

tupla=(2,5,7,9)
lista2=[]
lista5=[]
lista7=[]
lista9=[]
listaninguno=[]
for12
4 i in range(0,10):
  x=int(input("Ingrese un número"))
  if x%tupla[0]==0:
    lista2.append(x)
  elif x%tupla[1]==0:
    lista5.append(x)
  elif x%tupla[2]==0:
    lista7.append(x)
  elif x%tupla[3]==0:
    lista9.append(x)
  else: 
    listaninguno.append(x)

print("Multiplos de 2: " , lista2)
print("Multiplos de 5: ",lista5)
print("Multiplos de 7: ",lista7)
print("Multiplos de 9: ",lista9)
print("NO HUBO MULTIPLOS:", listaninguno)

#Progrmación orientada a objetos#
#herencia y polimorfismo#
#Cohesión se enfoca en que todo lo que se escriba este relacionado en el mismo scrip#"
"""Abstracción se que lo hace pero no cómo lo hace, ejm un print
acoplamiento como todas dependen de 1 puede presentarse fallas
encapsulamiento cuando se mete una operación en una función"""

perros=[]
for i in range(0,5):
  raza=input("Ingrese la raza de su canino: ") 
  nombre=input("Ingrese el nombre de su canino: ") 
  edad=input("Ingrese la edad de su canino: ") 
  peso=input("Ingrese la peso de su canino: ")
  diccionario={"raza": raza, "nombre": nombre, "edad": edad, "peso": peso, "Correr":correr, "ladrar": ladrar}
  perros.append(diccionario)
print(perros)



class perro:
  def _init_(self, raza, nombre, edad, peso):
    self.raza = raza
    self.nombre = nombre
    self.edad = edad
    self.peso = peso

  def mostrarinfo(self):
    print("el nombre del canino es: "+ self.nombre) 
    print("La edad del canino es: "+ self.edad)  
    print("El peso del canino es:"+ self.nombre)
    print("La edad del canino es"+ self,raza)

  def sonido(guau):
  print("el sonido que hace su perro es: sonido")

nombre=int(input"Ingrese el nombre de su canino")
raza=int(input("Ingrese la raza de su canino: ")) 
  edad=int(input("Ingrese la edad de su canino: ") 
  peso=input("Ingrese la peso de su canino: ")