# -*- coding: utf-8 -*-
"""Ejercicio clase 10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15giMBRYcSPZGKCZ0jq1lhTPrT2Y0HsoS
"""

print ("Bienvenido")
n1=int(input("Ingrese número uno: "))
n2=int(input("Ingrese número dos: "))
n3=int(input("Ingrese número tres: "))
n4=int(input("Ingrese número cuatro: "))
n5=int(input("Ingrese número cinco: "))

n1=n1*(n1+1)
n2=n2*(n2+1)
n3=n3*(n3+1)
n4=n4*(n4+1)
n5=n5*(n5+1)

print ("Sus resultados para cada número son")
print ("número uno: ", n1)
print ("número dos: ", n2)
print ("número tres: ", n3)
print ("número cuatro: ", n4)
print ("número cinco: ", n5)