# -*- coding: utf-8 -*-
"""ejercicioscorreción.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gt0uHlLa33SjKp3KZYukjiY4KHzOfa8m
"""

#corrección#
def par_impar(numero):

    if(numero%2)==0:
        return True
    else:
        return False
  
resultado=par_impar(2)

if resultado==True:
    print("El número es par")
else:
    print("El número es impar")

#ciclo#
lista=[]
for i in range(1,100):
  lista.append(i)
print(lista)

