# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E3kpmlx86V847iQhz1buDamGV--F2_o5
"""

numero1= int(input ("ingresa el numero 1 "))
numero2= int(input ("ingresa el numero 2 "))

suma = numero1 + numero2
print("el resultado de la suma es: " , suma)

resta = numero1 - numero2
print("el resultado de la resta es: ", resta)

division = numero1/numero2
print("el resultado de la division es " , division)

multiplicacion = numero1 * numero2
print("el resultado de la multiplicacion es: " , multiplicacion)

c1n1= float(input("ingresa la nota 1 del corte 1 "))
c1n2= float(input("ingresa la nota 2 del corte 1 "))
c1n3= float(input("ingresa la nota 2 del corte 1 "))
corte1=((c1n1+c1n2+c1n3)/3)

c2n1= float(input("ingresa la nota 1 del corte 2 "))
c2n2= float(input("ingresa la nota 2 del corte 2 "))
c2n3= float(input("ingresa la nota 2 del corte 2 "))
corte2=((c2n1+c2n2+c2n3)/3)

c3n1= float(input("ingresa la nota 1 del corte 3 "))
c3n2= float(input("ingresa la nota 2 del corte 3 "))
c3n3= float(input("ingresa la nota 2 del corte 3 "))
corte3=((c3n1+c3n2+c3n3)/3)

cortet=((corte1*0.2)+(corte2*0.2)+(corte3*0.6))

print("la nota final es: " , cortet)

prod1= float(input("ingresa el valor del producto 1 "))
prod2= float(input("ingresa el valor del producto 2 "))
prod3= float(input("ingresa el valor del producto 3 "))

iva1= (prod1+(prod1*0.19))
iva2= (prod2+(prod2*0.19))
iva3= (prod3+(prod3*0.19))
total= iva1+iva2+iva3
print("el total a pagar es: " , total)