# -*- coding: utf-8 -*-
"""Funciones.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktGBUNdAWCkBe04pLtqdtlftIGRXO8U_
"""

#Primera parte#
#ACTIVIDAD 1#
def multiplicacion():
  x=float(input("ingrese un número: "))
  x=x*(x+1)
  print("El resultado es: ", x)
for i in range(0,5):
    multiplicacion()

#ACTIVIDAD 2#
def multiplicacion():
    x=float(input("Ingrese un número: "))
    x=x*(x+1)
    return x
for i in range(0,5):
  Resultado=multiplicacion()
  print("Su resultado es: ",Resultado)

#ACTIVIDAD 3#
def suma():
  N=float(input("ingrese el primer número "))
  N=N+(N+1)
  print("su resultado es ", N)
def multiplicacion():
  N=float(input("ingrese el primer número "))
  Multiplicacion=N*(N+1)
  print("su resultado es ", Resultado)
def division():
  N=float(input("ingrese el primer número "))
  N=N/(N+1)
  print("su resultado es ", N)
def resta():
  N=float(input("ingrese el primer número "))
  N=N-(N+1)
  print("su resultado es ", N)
Opc=input("Seleccione la operación (A. suma // B. multiplicación // C. división // D. resta): ")
x=0
while x<=5:
  x+=1
  if Opc=="A":
     suma()
  elif Opc=="B":
     multiplicacion()
  elif Opc=="C":
     division()
  elif Opc=="D":
     resta()
  else: 
   print("Opción no válida")
   break