# -*- coding: utf-8 -*-
"""LISTAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktGBUNdAWCkBe04pLtqdtlftIGRXO8U_
"""

#SEGUNDA PARTE DE LA CLASE: LISTAS#
#ACTIVIDAD#
numeros_enteros= [1,2,3,4,5,6,7,8,9,10]
numeros_enteros[0]=20
numeros_enteros[6]="Hola mundo"
print(numeros_enteros[9])

valores_combinados= ["azul", 2.56, 1221, "ABC", 3.141516, "PLANTAS", 2.33, 3.44, 4, 1]
valores_combinados[0]=20
numeros_enteros[6]="Hola mundo"
print(valores_combinados[9])

valores_de_texto=["Ana", "Julian", "Mariana", "Sofia", "Susana", "Alejandra", "Maria", "Andy", "Jose", "Antonia"]
valores_de_texto[0]=20
numeros_enteros[6]="Hola mundo"
print(valores_de_texto[9])