# -*- coding: utf-8 -*-
"""Parcial 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DwgK2NWMTIwKza-qn7K8GddR3AMNRwFX
"""

class Planta:
  def __init__(self,especie,nombre,color,dias):
    self.especie = especie
    self.nombre = nombre
    self.color= color
    self.dias=dias

  def mostrar_info_planta(self):
    return f"La especie {self.especie} es una planta conocida como {self.nombre} y es de color {self.color}"


class Planta_fruto(Planta):
  def fruto(self):
    print("La especie " + self.especie + "es una planta conocida como " + self.nombre + "y es de color " + self.color)
    return f"La especie {self.especie} tiene fruto"

  def edad_planta(self):
    from datetime import date
    hoy = date.today()
    fecha = date()
    edad = hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day))
    if edad < 1:
      print(hoy-fecha)
    else:
     print(edad)


class Planta_flor(Planta):
  def flor(self):
    print("La especie " + self.especie + "es una planta conocida como " + self.nombre + "y es de color " + self.color)
    return f"La especie {self.especie} tiene flor"
    
  def edad_planta(self):
    from datetime import date
    hoy = date.today()
    fecha = date(2022, 2, 26)
    edad = hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day))
    if edad < 1:
      print(hoy-fecha)
    else:
     print(edad)

a= str(input("Especie: "))
b= str(input("Nombre: "))
c= str(input("Color: "))

planta1= Planta_fruto(a,b,c)
#planta1.fruto()
planta1.edad_planta()

def y():
  dias=hoy-fecha
  from datetime import date
  hoy = date.today()
  fecha = date(2022,2,26)
  edad = hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day))
  dias=hoy-fecha
  print(dias)
 
y()

def longevidad(self):
  if self.dias > 365 and self.dias < 730:
    print("La planta es anual")
  elif self.dias > 730 and self.dias < 1095:
    print("La planta es bienal")
  elif self.dias > 1095:
    print("La planta es perenne")

class Planta:
  def __init__(self,especie,nombre,color,dias):
    self.especie = especie
    self.nombre = nombre
    self.color= color
    self.dias=dias

  def mostrar_info_planta(self):
    return f"La especie {self.especie} es una planta conocida como {self.nombre} y es de color {self.color}."


class Planta_fruto(Planta):
  def fruto(self):
    print("La especie " + self.especie + "es una planta conocida como " + self.nombre + "y es de color " + self.color)
    return f"La especie {self.especie} tiene fruto"

  def edad_planta(self):
    from datetime import date
    hoy = date.today()
    fecha = date(2022,2,26)
    edad = hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day))
    dias=hoy-fecha
    print(dias)

  def longevidad(self):
    if self.dias > 365 and self.dias < 730:
      print("La planta es anual")
    elif self.dias > 730 and self.dias < 1095:
      print("La planta es bienal")
    elif self.dias > 1095:
      print("La planta es perenne")


class Planta_flor(Planta):
  def flor(self):
    print("La especie " + self.especie + "es una planta conocida como " + self.nombre + "y es de color " + self.color)
    return f"La especie {self.especie} tiene flor"
    
  def edad_planta(self):
    from datetime import date
    hoy = date.today()
    fecha = date(2022,2,26)
    edad = hoy.year - fecha.year - ((hoy.month, hoy.day) < (fecha.month, fecha.day))
    dias=hoy-fecha
    print(dias)

  def longevidad(self):
    if self.dias > 365 and self.dias < 730:
      print("La planta es anual")
    elif self.dias > 730 and self.dias < 1095:
      print("La planta es bienal")
    elif self.dias > 1095:
      print("La planta es perenne")


a= str(input("Especie: "))
b= str(input("Nombre: "))
c= str(input("Color: "))


planta1= Planta_fruto(a,b,c)
#planta1.fruto()
planta1.edad_planta()