# -*- coding: utf-8 -*-
"""Parcial 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q5E6zFT474DVBWC5by55UhQXarvd4HKZ
"""

#Parcial - punto 1
palabra=str(input("Ingrese una palabra: "))

def mostrar_letra ():
  for i in str(palabra):
    print(i)

mostrar_letra()


len(palabra)

#Prueba len()
palabra=str(input("Ingrese una palabra: "))
len(palabra)

#Parcial - punto 2
palabra=str(input("Ingrese una palabra: "))
lista=[]

def str_to_list():
  for i in str(palabra):
    if i == " ":
      continue
    lista.append(i)
  print(lista)

str_to_list()


len(palabra)

#Parcial - punto 3
x=5%2
print(x)

#Parcial - punto 4
lista1=[15,20,25,30]
lista2=[15,20,25,30]
print(lista1==lista2)

#Parcial - punto 5

def create_invoice():
  nombre= str(input("Ingresar nombre:"))
  
  producto1=input("Ingrese el producto:")
  valor1=int(input("Ingrese el valor:"))
  
  producto2=input("Ingrese el producto:")
  valor2=int(input("Ingrese el valor:"))
  
  producto3=input("Ingrese el producto:")
  valor3=int(input("Ingrese el valor:"))
  
  producto4=input("Ingrese el producto:")
  valor4=int(input("Ingrese el valor:"))
  
  suma=valor1+valor2+valor3+valor4
  
  dicc={"Nombre_comprador":nombre,"productos":[producto1,producto2,producto3,producto4],"total_compra":suma}  
  print(dicc)

create_invoice()

#Parcial - punto 5
num_productos=int(input("Ingrese el número de productos: "))


def create_invoice():
  nombre= str(input("Ingresar nombre:"))

  lista1=[]
  suma=0
  conteo=0
  while conteo < num_productos:
    producto=input("Ingrese el producto:")
    lista1.append(producto)
    valor=int(input("Ingrese el valor:"))
    conteo=conteo+1
    suma=suma + valor
  dicc={"Nombre_comprador":nombre,"Productos":lista1,"total_compra":suma}
  print(dicc)


create_invoice()

#Parcial - punto 5

def create_invoice():
  nombre= "Pepe"
  
  valor_prod1=1000
  
  valor_prod2=4000
  
  valor_prod3=2000
  
  valor_prod4=2000
  
  suma=valor_prod1+valor_prod2+valor_prod3+valor_prod4
  
  dicc={"Nombre_comprador":nombre,"productos":["producto1","producto2","producto3","producto4"],"total_compra":suma}  
  print(dicc)

create_invoice()

#Parcial - punto 6
def imprimir_numeros(lista):
  for i in lista:
    return i
numero = imprimir_numeros([2,7,5,10])
print(numero)

#Parcial - punto 7
def imprimir_numeros(lista):
  for i in lista:
    print(i)
numero = imprimir_numeros([2,7,5,10])

#Parcial - punto 8
if _name_=='_main_':
  a=int(numero())
  b=int(numero())
  suma=a+b
  resta=a-b
  multi=a*b

#Parcial - punto 9
lista=[1,2,3,4,2,6,1,8,2,10,1,12,2,14]

def caracteres_repetidos(lista):
  if len(lista) < 10 or len(lista) > 20:
    print("Error: cadena muy corto o muy larga")
  else:
    print("Número de veces que se repite cada elemento de la lista:")
    for i in lista:
      print(lista.count(i))

def eliminacion_duplicados(lista):
  print("Lista sin los valores repetidos:")
  listanueva=print(set(lista))

listanueva=set(lista)

def conversion_tupla(lista):
  tupla=tuple(listanueva)
  print("Tupla: ")
  print(tupla)

caracteres_repetidos(lista)
eliminacion_duplicados(lista)
conversion_tupla(lista)

tupla= tuple(listanueva)

num=int(input("Ingrese número: "))
if num < 20 and num > 100:
  print("Error")
else:
  for i in tupla:
    porcentaje=(i/100)*num
    print(porcentaje)


for i in tupla:
  import math as math
  log=i
  res= math.log(num, log)
  print(res)


for i in tupla:
  import math as math
  num1=i
  res= math.log(num1)
  print(res)


for i in tupla:
  import math as math
  log=10
  num2=i
  res= math.log(num2, log)
  print(res)

for i in tupla:
  multipli=num*i
  print(multipli)