# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcfiSJjQuiiftLoxJ4g1zxxlcqU7iHHa
"""

dato1=float(input("Ingrese dato 1: "))
x1=dato1+1
num=dato1*x1
print("Resultado: " , num)
dato2=float(input("Ingrese dato 2: "))
x2=dato2+1
num2=dato2*x2
print("Resultado: " , num2)
dato3=float(input("Ingrese dato 3: "))
x3=dato3+1
num3=dato3*x3
print("Resultado: " , num3)
dato4=float(input("Ingrese dato 4: "))
x4=dato4+1
num4=dato4*x4
print("Resultado: " , num4)
dato5=float(input("Ingrese dato 5: "))
x5=dato5+1
num5=dato5*x5
print("Resultado: " , num5)