# -*- coding: utf-8 -*-
"""programa 5 datos ssoc

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ELOniYvWrCwr8cUrLNzV7ZdktFzgVklP
"""

#Escribe un programa que capture 5 datos, y cada dato se multiplique por el mismo +1. 
#Crealo de forma larga, es decir, que no tenga while, ni for, solo input y operadores aritméticos básicos. 
#Luego sube tu código al repositorio en una carpeta que llamada: patrones repetitivos y dile a uno de tus compañeros que lo descargue. 
#Vamos a revisar si tu compañero entiende tu código. Tu compañero debe arreglar el código de manera que se usen ciclos para hacerlo más corto. 
#En promedio debe tener de 15 a 20 líneas de código con el ajuste debe quedar más o menos a la mitad.

num1= int(input("Ingrese número: "))
multi1= num1*(num1+1)
print(multi1)

num2= int(input("Ingrese número: "))
multi2= num2*(num1+1)
print(multi2)

num3= int(input("Ingrese número: "))
multi3= num3*(num1+1)
print(multi3)

num4= int(input("Ingrese número: "))
multi4= num4*(num1+1)
print(multi4)

num5= int(input("Ingrese número: "))
multi5= num5*(num1+1)
print(multi5)