# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xt-ZOkM_U2uUbm6F6ahMQ5kI2OBcrBh2
"""

n1= int(input("Ingrese el primer número "))
n2= int(input("Ingrese el segundo número "))

suma= n1+n2
print("El resultado de la suma es", suma)

n1= int(input("Ingrese el primer número"))
n2= int(input("ingrese el segundo número"))

resta= n1-n2
print("El resultado de la resta es", resta)

division= suma/resta
print("El resultado de la división es", division)

multiplicacion= suma*resta
print("El resultado de la multiplicación es", multiplicacion)



n1=float(input("Ingrese la nota 1 corte 1: "))
n2=float(input("Ingrese la nota 2 corte 1: "))
n3=float(input("Ingrese la nota 3 corte 1: "))

nota1=((n1+n2+n3)/3)*(0.2)

n1=float(input("Ingrese la nota 1 corte 2: "))
n2=float(input("Ingrese la nota 2 corte 2: "))
n3=float(input("Ingrese la nota 3 corte 2: "))

nota2=((n1+n2+n3)/3)*(0.2)

n1=float(input("Ingrese la nota 1 corte 3: "))
n2=float(input("Ingrese la nota 2 corte 3: "))
n3=float(input("Ingrese la nota 3 corte 3: "))

nota3=((n1+n2+n3)/3)*(0.6)

total= nota1+nota2+nota3
print("La nota final es: ",total)

s1=float(input("Ingrese el valor del producto 1: "))
s2=float(input("Ingrese el valor del producto 2: "))
s3=float(input("Ingrese el valor del producto 3: "))

p1=s1*0.19
p2=s2*0.19
p3=s3*0.19

totaliva=p1+p2+p2
print("El valor del iva es: ", totaliva)

totalfactura=s1+s2+s3+totaliva
print("El valor total a pagar es: ", totalfactura)