# -*- coding: utf-8 -*-
"""Quiz final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yV1crXc2eaFLJLKQuL3lGhhQzfdjH9A2
"""

class Persona:
  def __init__(self,nombre,apellido,edad,semestre,carrera):
    self.nombre = nombre
    self.apellido = apellido
    self.edad = edad
    self.semestre = semestre
    self.carrera = carrera

  def ver_persona(self):
    lista=[]
    contador=0
    while contador <3:
      A=str(input("Nombre del candidato: "))
      B=str(input("Apellido del candidato: "))
      C=str(input("Edad del candidato: "))
      D=str(input("Semestre que cursa: "))
      E=str(input("Carrera que cursa: "))
      dicc={
      "Nombre":{self.nombre},
      "Apellido":{self.apellido},
      "Edad":{self.edad},
      "Semestre":{self.semestre},
      "Carrera":{self.carrera}
      }
      lista.append(dicc)
      contador=contador +1
    return lista

candidato= Persona(A, B, C, D, E)
candidato.ver_persona()

class Crear_Votos:
  def __init__(self,candidato,votos):
    self.candidato = candidato
    self.votos = votos

    def votacion(self):
      contador=0
      lista=[]
      while contador <2:
        F= str(input("Número del candidato: "))
        G= str(input("Poner x para votar: "))
        lista.append(G)
        lista1=[]
        lista2=[]
        lista3=[]
        if F == 1:
          lista1.append(G)
        elif F == 2:
          lista2.append(G)
        elif F == 3:
          lista3.append(G)
        contador=contador+1

      while contador <2:
        if F == 1:
            dicc={  
            "Candidato1":len(lista1)
            }
        elif F == 2:
            dicc={
            "Candidato2": len(lista2)
            }
        elif F == 3:
            dicc3={
            "Candidato3": len(lista3)
            }
        contador=contador +1
      return dicc

voto= Crear_Votos(F, G)
voto.votacion()

class Crear_Votos:
  def __init__(self,candidato,votos):
    self.candidato = candidato
    self.votos = votos

  def votacion(self):
    contador=0
    lista=[]
    while contador <2:
      F= str(input("Número del candidato: "))
      G= str(input("Poner x para votar: "))
      lista.append(G)
      lista1=[]
      lista2=[]
      lista3=[]
      if F == 1:
        lista1.append(G)
      elif F == 2:
        lista2.append(G)
      elif F == 3:
        lista3.append(G)
    contador=contador+1
    dicc={  
    "Candidato1":len(lista1),
    "Candidato2": len(lista2),
    "Candidato3": len(lista3)
    }
    return dicc
    print(dicc)

voto= Crear_Votos(F, G)
voto.votacion()

class Persona:
  def __init__(self,nombre,apellido,edad,semestre,carrera):
    self.nombre = nombre
    self.apellido = apellido
    self.edad = edad
    self.semestre = semestre
    self.carrera = carrera

  def ver_persona(self):
    lista=[]
    contador=0
    while contador <3:
      A=str(input("Nombre del candidato: "))
      B=str(input("Apellido del candidato: "))
      C=str(input("Edad del candidato: "))
      D=str(input("Semestre que cursa: "))
      E=str(input("Carrera que cursa: "))
      dicc={
      "Nombre":{self.nombre},
      "Apellido":{self.apellido},
      "Edad":{self.edad},
      "Semestre":{self.semestre},
      "Carrera":{self.carrera}
      }
      lista.append(dicc)
      contador=contador +1
    return lista

candidato= Persona(A, B, C, D, E)
candidato.ver_persona()


class Crear_Votos:
  def __init__(self,candidato,votos):
    self.candidato = candidato
    self.votos = votos

  def votacion(self):
    contador=0
    lista1=[]
    lista2=[]
    lista3=[]
    while contador <2:
      F= str(input("Número del candidato: "))
      G= str(input("Poner x para votar: "))
      if F == 1:
        lista1.append(G)
      elif F == 2:
        lista2.append(G)
      elif F == 3:
        lista3.append(G)
    contador=contador+1
    dicc={  
    "Candidato1":len(lista1),
    "Candidato2": len(lista2),
    "Candidato3": len(lista3)
    }
    return dicc
    print(dicc)

class voto(Crear_Votos):
  pass

v= voto(F, G)
v.votacion()