# -*- coding: utf-8 -*-
"""Reuso-ajustes - Sara oquendo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DmolzcZT2iENPL-oEqDBiX_c_BdXfny5
"""

num1= int(input("Ingrese número: "))
multi1= num1*(num1+1)
print(multi1)

num2= int(input("Ingrese número: "))
multi2= num2*(num1+1)
print(multi2)

num3= int(input("Ingrese número: "))
multi3= num3*(num1+1)
print(multi3)

num4= int(input("Ingrese número: "))
multi4= num4*(num1+1)
print(multi4)

num5= int(input("Ingrese número: "))
multi5= num5*(num1+1)
print(multi5)



num=0

while num < 5:
  numero= int(input("Ingrese número: "))
  multi= numero*(numero+1)
  print("Resultado multiplicación: ", multi)
  num= num + 1