# -*- coding: utf-8 -*-
"""Semana 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uIBOTQVIoCeG3P7N7u2fnPvqFzR7zTnD
"""

opcionuser = str(input("Ingrese la opción que desee "))

if opcionuser == "A":
 print ("Opción de registro")
elif opcionuser == "B":
 print ("Opción de login")
else: 
 print ("No es válida la opción para el inicio de sesión")

numeroA = int(input("Ingrese el número "))
numeroB = int(input("Ingrese el número "))

suma= numeroA + numeroB
if numeroA > numeroB:
  print("El primer número es mayor que el segundo")
  resta= numeroA - numeroB
  print("El resultado de la resta es: ", resta)
else:
  print("El segundo número es mayor que el primero")
  resta= numeroB - numeroA
  print("El resultado de la resta es: ", resta)

numeroC = int(input("Ingrese el número para la multiplicación "))
multiplicacion = resta * numeroC
print("El resultado de la multiplicación es: ", multiplicacion)

numeroD = int(input("Ingrese el número para la división "))
if numeroD > numeroC:
 division = numeroD / numeroC
else:
 division = numeroC / numeroD
print("El resultado de la división es: ", division)

for i in range(1,101):
  if i % 2 ==0:
    continue
  else:
    print("Número impar")
    print(i)

numeroA = int(input("Ingrese el número "))
numeroB = int(input("Ingrese el número "))
suma= numeroA + numeroB
sumat= suma + numeroA + numeroB
conteo=0

while sumat < 100:
  if numeroA >= 40 or numeroB >= 40:
    break
  else:
    sumat= suma + numeroA + numeroB
    sumatotal= sumat + numeroA + numeroB
    print("El resultado de las sumas es: ", sumatotal)
    conteo=conteo+1
    
    #No supe cómo hacerlo funcionar

texto= str(input("Ingrese el la palabra "))

if len(texto) > 5:
  for i in texto:
    print(i)
  print("La cantidad de letras que contiene el texto es: ", len(texto))
else:
  print("Texto no válido")
  print("La cantidad de letras que contiene el texto es: ", len(texto))