# -*- coding: utf-8 -*-
"""Semana 12-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iKbYFDj34m61SeIjvgsa32pjmMnEn_Xi
"""

#sube los ajustes a un nuevo script llamado reúso-modularización
#Lo realicé con el código que le corregí a mi compañera, ya que ella no subió las correciones del mio

#Este es el código sin modularizar
num1= int(input("Ingrese número: "))
multi1= num1*(num1+1)
print(multi1)

num2= int(input("Ingrese número: "))
multi2= num2*(num1+1)
print(multi2)

num3= int(input("Ingrese número: "))
multi3= num3*(num1+1)
print(multi3)

num4= int(input("Ingrese número: "))
multi4= num4*(num1+1)
print(multi4)

num5= int(input("Ingrese número: "))
multi5= num5*(num1+1)
print(multi5)

num=0

while num < 5:
  numero= int(input("Ingrese número: "))
  multi= numero*(numero+1)
  print("Resultado multiplicación: ", multi)
  num= num + 1

#Código modularizado

opcion=str(input("Ingresa la opcion A,B,C o D: "))

def suma():
    num=int(input("Ingresa un número "))
    num=num+(num+1)
    print("El resultado es ", num)

def resta():
    num=int(input("Ingresa un número "))
    num=num-(num+1)
    print("El resultado es ", num)

def multiplicacion():
    num=int(input("Ingresa un número "))
    num=num*(num+1)
    print("El resultado es ",num)

def division():
    num=int(input("Ingresa un número "))
    num=num/(num+1)
    print("El resultado es ", num)

z=0
while z<5:
    if opcion=="A":
        suma()
    elif opcion=="B":
        resta()
    elif opcion=="C":
        multiplicacion()
    elif opcion=="D":
        division()
    z=z+1