# -*- coding: utf-8 -*-
"""Semana 13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LOTt6fRmMa1aT5u6wjq_oyPnquuFl_4z
"""

#Listas
numerica=[200,201,202,203,204,205,206,207,208,209]
combinada=["Bruno",2,"Estrellita",1,1999,18,"Micro","viajar",47,"amor"]
texto=["Petri","bacteria","bata","guantes","microscopio","virus","inmunología","Neumococo","ARN","ADN"]

print("Listas: ")
print(numerica)
print(combinada)
print(texto)

numerica[0]=20
combinada[0]=20
texto[0]=20

numerica[5]="Hola mundo"
combinada[5]="Hola mundo"
texto[5]="Hola mundo"

print("Listas modificadas: ")
print(numerica)
print(combinada)
print(texto)

print("Última posición de las listas: ")
print (numerica[9])
print (combinada[9])
print (texto[9])