# -*- coding: utf-8 -*-
"""Semana 14

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_b5w-1d3EhHbPgzQ5zSLzlUVdDSVJl1
"""

lista = [] 
for i in range(0,10):
  num = int(input("Ingrese el número "))
  lista.append (num)
print(lista)

print(len(lista))

tupla= (1,2,3,4,5,True,False,("F","C","A"))
print("Elementos de la primera y última posición de la tupla:")
print(tupla[0])
print(tupla[7])

tupla1= (1,2,3,4,5,"Carro","Luca",11,9,(1,2))
tupla2=("mamá","papá","hermano","perro", "yo")
tupla3=(1,2,3,4,5,6,7,8)

print("Cantidad de elementos de la tupla, la tupla1, la tupla2 y la tupla3:")
print(len(tupla))
print(len(tupla1))
print(len(tupla2))
print(len(tupla3))

print("Comparación:")

#Parcial
#Identificación errores del código
def par_impar(numero):
    if(numero%2):          #dos puntos
        return "Es par"
    else:                 #dos puntos
        return False
    
resultado = par_impar(2)
if(resultado):
    print("El número es par")
else:                    #dos puntos
    print("El número es impar")

#Parcial
#Lista con números del 1 al 100, usando for o while
lista=[]
for i in range(1,101):
  lista.append (i)
print(lista)

#Crea un diccionario donde almacenes la información de tus clases (5) vistas este semestre como nombre materia, nombre de profesor y horario
#Agrega al diccionario los campos necesarios para conocer el nombre del edificio y número del salón de clase
#Elimina el primer y último elemento del diccionario

#No entendí muy bien cómo se hacía el ejercicio asi que lo hice dos veces de diferentes maneras.
dicci={
    "Materia1":"Física y laboratorio",
    "Profesor1":"Juan Manuel Jaramillo",
    "Horario1":"Lunes de 8am a 10am",
    "Materia2":"Álgebra lineal",
    "Profesor2":"Walter Andrés Acevedo",
    "Horario2":"Miércoles de 11:30am a 2:30pm",
    "Materia3":"Botánica y sistemática vegetal",
    "Profesor3":"Camila Martinez",
    "Horario3":"Lunes de 10am a 1pm",
    "Materia4":"Contexto político",
    "Profesor4":"Wilder Fernando Suarez",
    "Horario4":"Jueves de 3pm a 6pm",
    "Materia5":"Química analítica",
    "Profesor5":"Lucas Hernan Blandon",
    "Horario5":"Jueves de 10:30am a 12pm"
}

dicci["Nombre del edificio1"]= "Ingenierias"
dicci["Nombre del edificio2"]= "Bloque 33"
dicci["Nombre del edificio3"]= "Bloque 18"
dicci["Nombre del edificio4"]= "Bloque 35"
dicci["Nombre del edificio5"]= "Bloque 14"
dicci["Número del aula1"]= "19-405"
dicci["Número del aula2"]= "33-202"
dicci["Número del aula3"]= "18-301"
dicci["Número del aula4"]= "35-501"
dicci["Número del aula5"]= "14-203"

del dicci["Número del aula5"]
del dicci["Materia1"]

   
print(dicci)

#Crea un diccionario donde almacenes la información de tus clases (5) vistas este semestre como nombre materia, nombre de profesor y horario
#Agrega al diccionario los campos necesarios para conocer el nombre del edificio y número del salón de clase
#Elimina el primer y último elemento del diccionario

dicci={
    "Materia":str(input("Materia: ")),
    "Profesor":str(input("Profesor: ")),
    "Horario":input("Horario: ")
}

dicci["Nombre del edificio"]= input("Nombre del edificio: ")

dicci["Número del aula"]= input("Número del aula: ")


del dicci["Número del aula"]
del dicci["Materia"]

   
print(dicci)

#Crea un diccionario con listas de nombres de verduras y frutas (10), separadas por el color. Estructura esperada {rojo: ["manzana", "tomate"]}
dicci1={
    "Rojo":["manzana","tomate"],
    "Verde":["pera","coliflor"],
    "Morado":["uva","remolacha"],
    "Amarillo":["banano","pimentón amarillo"],
    "Naranja":["Naranja","calabaza"],
    "Azul":["arándanos","berenjena"],
    "Café":["zapote","yuca"],
    "Rosado":["granada","rábano"],
    "Negro":["grosella negra","rábano negro"],
    "Blanco":["guanábana","cebolla"],
}
print(dicci1)