# -*- coding: utf-8 -*-
"""Semana 16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LQp20UsS9ypVW9GBdE-ya4NfI0xJB4u4
"""

class Bacteria:
  def __init__(self,especie,tamaño,gram,respiracion,morfologia):
    self.especie = especie
    self.tamaño = tamaño
    self.gram = gram
    self.respiracion = respiracion
    self.morfologia = morfologia

  def mostrar_info(self):
    return f"{self.especie} es una bacteria gram {self.gram} que mide {self.tamaño}. Tiene una morfología de {self.morfologia} y su respiración es {self.respiracion}"

class miBacteria(Bacteria):
  pass

b = miBacteria("Yersinia pestis","2.3 nm","negativa","anaerobica","bacilo")
b.mostrar_info()

class Figura:
  def __init__(self,base,altura):
    self.base = base
    self.altura = altura

  def calculo_area(self):
    pass

class Triangulo(Figura):
  def calculo_area(self):
    calculo= self.base * self.altura
    return calculo

t= Triangulo(3,4)
print(t.calculo_area())

class Cuadrado(Figura):
  def calculo_area(self):
    calculo= self.base * self.altura
    return calculo

c= Cuadrado(3,3)
print(c.calculo_area())

#Desafio 1
def saludar():
  print("Hola mundo")

saludar()

#Desafio 2
lista=[]
for i in range(0,101):
  lista.append(i)

print(lista)

#Desafio 3
dicc={
    "Nombre":input("Nombre: "),
    "Categoria":input("Categoria: "),
    "Tiempo_duracion":input("Tiempo de duración: ")
}

print(dicc)
#No recuerdo en qué contexto estaban los campos a rellenar.

#Desafio 4
class Vehiculo:
  def __init__(self,marca,kilometraje,color):
    self.marca = marca
    self.kilometraje = kilometraje
    self.color = color

  def mostrar_info(self):
    return f"El vehiculo {self.marca} de {self.kilometraje} y con un color {self.color}"

class Carro(Vehiculo):
  pass

c = Carro("BMW","100k/h","morado")
c.mostrar_info()

#Desafio 5
lista=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

def multiplo(lista):
  for i in lista:
    if i%2==0:
      print("Buzz")
    elif i%5==0:
      print("Fizz")
    
multiplo(lista)