# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cKpB6Hd20WzXFVCAL06vsrxm1jSfNeQr
"""

numero1 = int(input("ingrese un numero para la suma:"))
numero2 = int(input("ingrese otro numero para la suma:"))

suma= numero1 + numero2
print ("El resultado de la suma es:", suma )


a= int(input("ingrese un numero para la resta:"))
b = int(input("ingrese otro numero para la resta:"))

resta= a-b 
print("El resultado de la resta es:", resta)

resultado1= suma/resta 
print("El resultado de la division es:", resultado1)

resultado2= suma*resta 
print("El resultado de la multiplicacion es:",resultado2)

nota1=float(input("Ingrese la primer nota:"))
nota2=float(input("Ingrese la segunda nota:"))
nota3=float(input("Ingrese la tercera nota:"))

corte1=(nota1+nota2+nota3)/3*0.2
print("El resultado del corte 1 es:",corte1)

notaA=float(input("Ingrese la primer nota:"))
notaB=float(input("Ingrese la segunda nota:"))
notaC=float(input("Ingrese la tercera nota:"))

corte2=(notaA+notaB+notaC)/3*0.2
print("El resultado del corte 2 es:",corte2)


notax=float(input("Ingrese la primer nota:"))
notay=float(input("Ingrese la segunda nota:"))
notaz=float(input("Ingrese la tercera nota:"))

corte3=(notax+notay+notaz)/3*0.6
print("El resultado del corte 3 es:",corte3)

notafinal=(corte1+corte2+corte3)/3
print("La nota final es:",notafinal)

producto1=int(input("Ingrese el numero del primer producto:"))
producto2=int(input("Ingrese el numero del segundo producto:"))
producto3=int(input("Ingrese el numero del tercer producto:"))

total1=producto1*1.19
print("El producto 1 con IVA incluido tiene un valor de:",total1)

total2=producto2*1.19
print("El producto 2 con IVA incluido tiene un valor de:",total2)

total3=producto3*1.19
print("El producto 3 con IVA incluido tiene un valor de:",total3)

totalfinal=total1+total2+total3
print("El total con IVA incluido tiene un valor de:",totalfinal)