# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cxun82kWlVStnE29A3Q1cxvMl2wgKefB
"""

numero1 = int(input("Ingrese un número para la suma "))
numero2 = int(input("Ingrese un número para la suma "))

suma = numero1 + numero2
print("El resultado de la suma es: ", suma)

numero3 = int(input("Ingrese un número para la resta "))
numero4 = int(input("Ingrese un número para la resta "))

resta = numero3 - numero4
print("El resultado de la resta es: ", resta)

print("División entre el resultado de suma y resta")
division = suma/resta
print("El resultado de la división es: ", division)

print("Multiplicación entre el resultado de suma y resta")
multiplicacion = suma*resta
print("El resultado de la multiplicación es: ", multiplicacion)

nota1corte1 = float(input("Ingrese la nota 1 del corte 1 "))
nota2corte1 = float(input("Ingrese la nota 2 del corte 1 "))
nota3corte1 = float(input("Ingrese la nota 3 del corte 1 "))
suma1 = nota1corte1 + nota2corte1 + nota3corte1
division1 = suma1/3
notacorte1 = division1 * 0.2

nota1corte2 = float(input("Ingrese la nota 1 del corte 2 "))
nota2corte2 = float(input("Ingrese la nota 2 del corte 2 "))
nota3corte2 = float(input("Ingrese la nota 3 del corte 2 "))
suma2 = nota1corte2 + nota2corte2 + nota3corte2
division2 = suma2/3
notacorte2 = division2 * 0.2

nota1corte3 = float(input("Ingrese la nota 1 del corte 3 "))
nota2corte3 = float(input("Ingrese la nota 2 del corte 3 "))
nota3corte3 = float(input("Ingrese la nota 3 del corte 3 "))
suma3 = nota1corte3 + nota2corte3 + nota3corte3
division3 = suma3/3
notacorte3 = division3 * 0.6

notafinal = notacorte1 + notacorte2 + notacorte3
print("La nota final es ", notafinal)

producto1 = float(input("Ingrese el valor del producto 1 "))
producto2 = float(input("Ingrese el valor del producto 2 "))
producto3 = float(input("Ingrese el valor del producto 3 "))

iva1 = producto1*0.19
iva2 = producto2*0.19
iva3 = producto3*0.19

suma1 = iva1 + iva2 + iva3 
suma2 = producto1 + producto2 + producto3
sumatotal = suma1 + suma2
print("Valor total a pagar: ", sumatotal)