# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Bnu92mq3VEH1Ug6NAOZfAEnJDT6l8y8
"""

n1= int(input("ingrese primer numero"))
n2=int(input("ingrese segundo numero"))
n3=int(input("ingrese tercer numero"))
n4=int(input("ingrese cuarto numero"))
n5=int(input("ingrese quinto numero"))
s1=(n1*(n1+1))
s2=(n2*(n2+1))
s3=(n3*(n3+1))
s4=(n4*(n4+1))
s5=(n5*(n5+1))
print("la suma 1 es ", s1)
print("la suma 2 es ", s2)
print("la suma 3 es ", s3)
print("la suma 4 es ", s4)
print("la suma 5 es ", s5)