# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XypXVTRHu_CDGFWG0ngTJNfPLP9Kjhfm
"""

print ("digite los numeros para la suma")
num1= int(input("ingrese el primer numero: "))
num2= int(input("ingrese el segundo numero: "))
suma=num1+num2
print ("digite los numeros para la resta")
num3= int(input("ingrese el primer numero: "))
num4= int(input("ingrese el segundo numero: "))
resta=num3-num4
print ("el resultado de la suma es:", suma )
print ("el resultado de la resta es:", resta )
multiplicacion=suma*resta
division=suma/resta
print ("el resultado de la multiplicacion es:", multiplicacion )
print ("el resultado de la division es:", division )

print ("digite las notas para el corte 1: ")
cort1not1= float(input("ingrese la primera nota: "))
cort1not2= float(input("ingrese la segunda nota: "))
cort1not3= float(input("ingrese la tercera nota: "))
print ("digite las notas para el corte 2: ")
cort2not1= float(input("ingrese la primera nota: "))
cort2not2= float(input("ingrese la segunda nota: "))
cort2not3= float(input("ingrese la tercera nota: "))
print ("digite las notas para el corte 3: ")
cort3not1= float(input("ingrese la primera nota: "))
cort3not2= float(input("ingrese la segunda nota: "))
cort3not3= float(input("ingrese la tercera nota: "))

corte1= (((cort1not1+cort1not2+cort1not3)/3)*0.2)
corte2= (((cort2not1+cort2not2+cort2not3)/3)*0.2)
corte3= (((cort3not1+cort3not2+cort3not3)/3)*0.6)
total= corte1+corte2+corte3
print ("corte 1: ", corte1)
print ("corte 2: ", corte2)
print ("corte 3: ", corte3)
print ("Total: ", total)

precio1= float(input("ingrese el precio del producto 1: "))
precio2= float(input("ingrese el precio del producto 2: "))
precio3= float(input("ingrese el precio del producto 3: "))

total1=(precio1*0.19)
total2=(precio2*0.19)
total3=(precio3*0.19)
print ("el precio del producto 1 es: ", total1)
print ("el precio del producto 2 es: ", total2)
print ("el precio del producto 3 es: ", total3)