# -*- coding: utf-8 -*-
"""uwu2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1joj30ZbiHyFsTzDEXvphQj5yzVtOWO07
"""

numero1=int(input("Ingrese un número para la suma "))
numero2=int(input("Ingrese un número para la suma "))
suma= numero1 + numero2
print("El resultado de la suma es: ", suma)

numero1=float(input("Ingrese la primera nota del corte 1: "))
numero2=float(input("Ingrese la segunda nota del corte 1: "))
numero3=float(input("Ingrese la tercera nota del corte 1: "))
numero4=float(input("Ingrese la primera nota del corte 2: "))
numero5=float(input("Ingrese la segunda nota del corte 2: "))
numero6=float(input("Ingrese la tercera nota del corte 2: "))
numero7=float(input("Ingrese la primera nota del corte 3: "))
numero8=float(input("Ingrese la segunda nota del corte 3: "))
numero9=float(input("Ingrese la tercera nota del corte 3: "))
c1= ((numero1 + numero2 + numero3)/3) * 0.2
c2= ((numero4 + numero5 + numero6)/3) * 0.2
c3= ((numero7 + numero8 + numero9)/3) * 0.6
total= c1 + c2 + c3
print( "Total: ", total)

numero1=float(input("Ingrese el precio del primer producto: "))
numero2=float(input("Ingrese el precio del segundo producto: "))
numero3=float(input("Ingrese el precio del tercer producto: "))
iva1= numero1 * 0.19
iva2= numero2 * 0.19
iva3= numero3 * 0.19
print("El iva para el producto 1 es: ", iva1)
print("El iva para el producto 2 es: ", iva2)
print("El iva para el producto 3 es: ", iva3)
totalapagar= numero1 + numero2 + numero3 + iva1 + iva2 + iva3
print("El total a pagar es de:", totalapagar)