# -*- coding: utf-8 -*-
"""Clase_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYxTC1kNE3UFeFy2qtSnp36Y0Da-Cwpa
"""

numero1=float(input("ingrese un numero para la operacion A "))
numero2=float(input("ingrese un numero para la operacion B "))
numero3=float(input("ingrese un numero para la operacion C "))
numero4=float(input("ingrese un numero para la operacion D "))
numero5=float(input("ingrese un numero para la operacion E "))

suma1= numero1+ 1
multiplicacion1= numero1* suma1
print("el resultado de la operacion A es:", multiplicacion1)

suma2= numero2+ 1
multiplicacion2= numero2* suma2
print("el resultado de la operacion B es:", multiplicacion2)

suma3= numero3+ 1
multiplicacion3= numero3* suma3
print("el resultado de la operacion C es:", multiplicacion3)

suma4= numero4+ 1
multiplicacion4= numero4* suma4
print("el resultado de la operacion D es:", multiplicacion4)

suma5= numero5+ 1
multiplicacion5= numero5* suma5
print("el resultado de la operacion E es:", multiplicacion5)