# -*- coding: utf-8 -*-
"""Clase 10 Ana M Alzate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4TayJgu3xgipIOcJgoBJf1VlO-HimGd
"""

#EJERCICIO 1
for i in range(0,5):
 num1 = int(input("Ingresa un número"))
 multiplicacion = num1*(num1+1)
 print(multiplicacion)

#EJERCICIO 2
opcion= input("Ingresa la opción deseada: A (multiplicación), B (suma), C (resta) o D (división)")
for i in range(0,5):
  num = int(input("Ingresa un número"))
  if opcion == "A":
   operacion = num*(num+1)
  
  elif opcion == "B":
   operacion = num+(num+1)

  elif opcion == "C":
   operacion = num-(num+1)

  elif opcion == "D":
   operacion = num/(num+1)

  print(operacion)