# -*- coding: utf-8 -*-
"""Clase_10_ReptAna

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYxTC1kNE3UFeFy2qtSnp36Y0Da-Cwpa
"""

num1  =  int ( input ( "Ingresa el primer numero" ))
num2  =  int ( input ( "Ingresa el segundo numero" ))
num3  =  int ( input ( "Ingresa el tercer numero" ))
num4  =  int ( input ( "Ingresa el cuarto numero" ))
num5  =  int ( input ( "Ingresa el quinto numero" ))

op1  =  num1 * ( num1 + 1 )
op2  =  num2 * ( num2 + 1 )
op3  =  num3 * ( num3 + 1 )
op4  =  num4 * ( num4 + 1 )
op5  =  num5 * ( num5 + 1 )

print ( "resultado del primer numero: ", op1 )
print ( "resultado del segundo numero: ", op2 )
print ( "resultado del tercer numero: ", op3 )
print ( "resultado del cuarto numero: ", op4 )
print ( "resultado del quinto numero: ", op5 )

for i in range(0, 5):
  num  =  int ( input ( "Ingresa un numero: " ))
  suma= num + 1
  multiplicacion= num * suma
  print("el resultado de la operacion es:", multiplicacion)

opcion= ( input ( "Ingresa el nombre de la operacion que quieres realizar: "))
for i in range(0, 5):
  num  =  int ( input ( "Ingresa un numero: " ))
  if opcion=="multiplicacion":
    operacion= num * (num + 1)
  elif opcion=="suma":
    operacion= num + (num + 1)
  elif opcion=="resta":
    operacion= num - (num + 1)
  elif opcion=="division": 
    operacion= num / (num + 1)
  print("el resultado de la operacion es:", operacion)