numero1=float(input("escriba el primer número: "))
suma=numero1 *(numero1 + 1)
print("el resultado de la suma es ", suma)
numero2=float(input("escriba el segundo número: "))
suma=numero2 *(numero2 + 1)
print("el resultado de la suma es ", suma)
numero3=float(input("escriba el tercer número: "))
suma=numero3 *(numero3 + 1)
print("el resultado de la suma es ", suma)
numero4=float(input("escriba el cuarto número: "))
suma=numero4 *(numero4 + 1)
print("el resultado de la suma es ", suma)
numero5=float(input("escriba el quinto número: "))
suma=numero5 *(numero5 + 1)
print("el resultado de la suma es ", suma)
