# -*- coding: utf-8 -*-
"""Ejercicio reescrito

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F1AMnh3ZQgFdthghCwiFvOKbf7U5dRkT

Código realizado por Julián Marulanda
"""

numero1=float(input("escriba el primer número: "))
suma=numero1 *(numero1 + 1)
print("el resultado de la suma es ", suma)
numero2=float(input("escriba el segundo número: "))
suma=numero2 *(numero2 + 1)
print("el resultado de la suma es ", suma)
numero3=float(input("escriba el tercer número: "))
suma=numero3 *(numero3 + 1)
print("el resultado de la suma es ", suma)
numero4=float(input("escriba el cuarto número: "))
suma=numero4 *(numero4 + 1)
print("el resultado de la suma es ", suma)
numero5=float(input("escriba el quinto número: "))
suma=numero5 *(numero5 + 1)
print("el resultado de la suma es ", suma)

"""Código modificado por Alejandra Bedoya"""

print ("Bienvenido")
print ("Menú de Opciones")
print ("A. SUMA")
print ("B. RESTA")
print ("C. MUTIPLICACIÓN")
print ("D. DIVISIÓN")
x=str(input("Operación que desea realizar: "))

i=0

if(x=="A"):
  while i < 5:
    n=float(input("ingrese un número "))
    n+(n+1)
    print (n)
elif (x=="B"):
  while i < 5:
    n=float(input("ingrese un número "))
    n*(n+1)
    print (n)
elif (x=="C"):
  while i < 5:
    n=float(input("ingrese un número "))
    n-(n+1)
    print (n)
elif (x=="D"):
  while i < 5:
    n=float(input("ingrese un número "))
    n-(n+1)
    print (n)