# -*- coding: utf-8 -*-
"""Clase 10 Ana M Alzate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4TayJgu3xgipIOcJgoBJf1VlO-HimGd
"""

num1 = int(input("Ingresa el primer número"))
num2 = int(input("Ingresa el segundo número"))
num3 = int(input("Ingresa el tercer número"))
num4 = int(input("Ingresa el cuarto número"))
num5 = int(input("Ingresa el quinto número"))

op1 = num1*(num1+1)
op2 = num2*(num2+1)
op3 = num3*(num3+1)
op4 = num4*(num4+1)
op5 = num5*(num5+1)

print(op1)
print(op2)
print(op3)
print(op4)
print(op5)