# -*- coding: utf-8 -*-
"""patrón repetitivo Sofía García.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1guh5_D8DR9KQwdSe-dmp0MIPMg57ZS97
"""

N1=float(input("ingrese el primer número "))
Nuno=N1+1
Multiplicacion1=N1*Nuno
print("su resultado es ", Multiplicacion1)
N2=float(input("ingrese el segundo número "))
Ndos=N2+1
Multiplicacion2=N2*Ndos
print("su resultado es ", Multiplicacion2)
N3=float(input("ingrese el tercero número "))
Ntres=N3+1
Multiplicacion3=N3*Ntres
print("su resultado es ", Multiplicacion3)
N4=float(input("ingrese el cuarto número "))
Ncuatro=N4+1
Multiplicacion4=N4*Ncuatro
print("su resultado es ", Multiplicacion4)
N5=float(input("ingrese el quinto número "))
Ncinco=N5+1
Multiplicacion5=N5*Ncinco
print("su resultado es ", Multiplicacion5)