# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Jz6hLIr5KsMV0KPFnRi2SBCaa4lgXIg
"""

letra = input("digite la letra: ")
if letra == 'A':
  print ("Opcion de registro")
elif letra == 'B':
    print ("Opcion de login")
else:
  print ("Es invalido")

resta = 0
num1 = int(input("digite el pirmer numero: "))
num2 = int(input("digite el segundo numero: "))
if num1<num2:
  resta=num2-num1
  print (num2-num1)
else:
  resta=num1-num2
  print (resta)

num3 = int(input("digite el tercer numero: "))
multi=resta*num3
print (multi)

num4 = int(input("digite el cuarto numero numero: "))

if num3<num4:
  print ("el numero ", num4 ," es el dividendo y el numero", multi ," el divisor")
else:
  print ("el numero ", multi ," es el dividendo y el numero", num4 ," el divisor")

for i in range(1, 100):
  if (i%2 != 0):
    print(i)

suma=0
num1 = int(input("digite el primer numero: "))
num2 = int(input("digite el segundo numero: "))

while suma < 100:
  if num1 < 40 or num2 < 40:
    print (suma)
    suma=suma+num1+num2
  else:
    break

tamaño=0
palabra = input("digite la palabra: ")
for i in palabra:
    print(i)
    tamaño=tamaño+1

print ("el tmaño de la palabra es de ", tamaño, " letras")

num1 = int(input("digite el primer numero: "))
print (((num1*num1)+1))
num2 = int(input("digite el segundo numero: "))
print (((num2*num2)+1))
num3 = int(input("digite el tercer numero: "))
print (((num3*num3)+1))
num4 = int(input("digite el cuarto numero: "))
print (((num4*num4)+1))
num5 = int(input("digite el quinto numero: "))
print (((num5*num5)+1))

print ("Bienvenido")
n1=int(input("Ingrese número uno: "))
n2=int(input("Ingrese número dos: "))
n3=int(input("Ingrese número tres: "))
n4=int(input("Ingrese número cuatro: "))
n5=int(input("Ingrese número cinco: "))

n1=n1*(n1+1)
n2=n2*(n2+1)
n3=n3*(n3+1)
n4=n4*(n4+1)
n5=n5*(n5+1)

print ("Sus resultados para cada número son")
print ("número uno: ", n1)
print ("número dos: ", n2)
print ("número tres: ", n3)
print ("número cuatro: ", n4)
print ("número cinco: ", n5)

opc=int(input("¿que opcion desea realizar?\n 1)suma \n 2)resta \n 3)multiplicación \n 4)division \n"))
if (opc == 1 or 4):
  for i in range(1, 6):
    num = int(input("Ingrese número "+str(i)+": "))
    print ((num*num)+1)
if (opc == 2):
  for i in range(1, 6):
    num = int(input("Ingrese número "+str(i)+": "))
    print ((num-num)+1)
if (opc == 3):
  for i in range(1, 6):
    num = int(input("Ingrese número "+str(i)+": "))
    print ((num*num)+1)