# -*- coding: utf-8 -*-
"""Reuso-ajustes Mariana Garcés.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cFWRWI9cY7BiAiVSZBFZ_cMW78tpZcY3
"""

for i in range(0,5):
  num=float(input("Ingrese número: "))
  nummult=num+1
  Multiplicacion=num*nummult
  print("su resultado es: ", Multiplicacion)

opción=input("¿Qué desea realizar? A. Suma // B. Resta // C. Multiplicación // D. División ")
for i in range(0,5):
    num=float(input("Ingrese número: "))
    num2=num+1
    if opción=="A":
      operación=num+num2
    elif opción=="B":
      operación=num-num2
    elif opción=="C":
      operación=num*num2
    elif opción=="D":
      operación=num/num2
    print("su resultado es: ", operación)