# -*- coding: utf-8 -*-
"""Reuso ajustos Sofía García.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktGBUNdAWCkBe04pLtqdtlftIGRXO8U_
"""

intentos=0
while intentos < 5:
  dato1=float(input("Ingrese un dato: "))
  num1=dato1*(dato1+1)
  print("Resultado: " , num1)
  intentos += 1

x= input ("¿Qué operación desea hacer? A.MULTIPLICACIÓN   B. SUMA   C. RESTA   D. DIVISIÓN")

D2= int(input ("Ingrese un número "))
D1= int(input ("Ingrese un número "))

if  x=="A" :
  MUL=D1*D2
  print("Resultado: " , MUL)

elif x=="B" :
    SUMA=D1+D2
    print("Resultado: " , SUMA)

elif x=="C" :
  RESTA=D1-D2
  print("Resultado: " , RESTA)

elif x=="D" :
  DIV=D1/D2
  print("Resultado: " , DIV)

else:
  print("NO ingresó una opción válida " )