# -*- coding: utf-8 -*-
"""Semana 12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16WyBaqpW6sXEHgTSvjJEpmcLO1DvMCfd
"""

dato1= int(input("Ingrese dato 1 "))
operacion1= dato1*dato1+1
print("Resultado operación con dato 1: ", operacion1)

dato2= int(input("Ingrese dato 2 "))
operacion2= dato2*dato2+1
print("Resultado operación con dato 2: ", operacion2)

dato3= int(input("Ingrese dato 3 "))
operacion3= dato3*dato3+1
print("Resultado operación con dato 3: ", operacion3)

dato4= int(input("Ingrese dato 4 "))
operacion4= dato4*dato4+1
print("Resultado operación con dato 4: ", operacion4)

dato5= int(input("Ingrese dato 5 "))
operacion5= dato5*dato5+1
print("Resultado operación con dato 5: ", operacion5)