# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dbvB-3wq-bIbylEm0Fi24L8uyZHI1yrU
"""

num1 = int(input("ingrese numero 1"))
num2 = int(input("ingrese numero 2"))
num3 = int(input("ingrese numero 3"))
num4 = int(input("ingrese numero 4"))
num5 = int(input("ingrese numero 5"))

o1 = num1*(num1+1)
print ("el resultado es", o1)
o2 = num2*(num2+1)
print ("el resultado es", o2)
o3 = num3*(num3+1)
print ("el resultado es", o3)
o4 = num4*(num4+1)
print ("el resultado es", o4)
o5= num5*(num5+1)
print ("el resultado es", o5)