# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcfiSJjQuiiftLoxJ4g1zxxlcqU7iHHa
"""

dato1=int(input("Ingrese el primer número"))
respuesta1=dato1*(dato1 +1)
print("La respuesta es:", respuesta1)

dato2=int(input("Ingrese el segundo número"))
respuesta2=dato2*(dato2+1)
print("La respuesta 2 es:",respuesta2)

dato3=int(input("Ingrese el tercer número"))
respuesta3=dato3*(dato3+1)
print("La respuesta 3 es:", respuesta3)

dato4=int(input("Ingrese el cuarto número"))
respuesta4=dato4*(dato4+1)
print("La respuesta 4 es: ",respuesta4)

dato5=int(input("Ingrese el quinto número"))
respuesta5=dato5*(dato5+1)
print("La respuesta 5 es:",respuesta5)

menu=input("¿Qué operación quiere realizar? 1.Suma; 2.Resta; 3.Multiplicación; 4.División")
for i in range(0,5):
    num=float(input("Ingrese número: "))
    num2=num+1
    if menu=="1":
      operación=num+num2
    elif menu=="2":
      operación=num-num2
    elif menu=="3":
      operación=num*num2
    elif menu=="4":
      operación=num/num2
print("su resultado es: ", operación)